version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: customerdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/customerdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example

  proxy:
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app

volumes:
  db_data:
