spring:
  datasource:
    url: jdbc:h2:file:./data/customerdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  session:
    timeout: 30d
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=5000,expireAfterWrite=30d
    cache-names:
      - sessions

server:
  port: 8080
  forward-headers-strategy: framework
