spring:
  datasource:
    url: jdbc:mysql://db:3306/customerdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: example
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  session:
    timeout: 30d
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=5000,expireAfterWrite=30d
    cache-names:
      - sessions

server:
  port: 8080
  forward-headers-strategy: framework
